#!/bin/sh
set -e

echo "Running tests and coverage before push..."
if [ -z "$SONAR_TOKEN" ]; then
  echo "SONAR_TOKEN is not set. Skipping SonarCloud scan."
  npm run test:unit
  npm run test:unit:coverage
  npm run test:e2e
  exit 0
fi
npm run prepush
npm run sonar:summary
npm run test:e2e
