sonar.projectKey=rfonte_brazildecoded.webapp
sonar.organization=rfonte
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.exclusions=node_modules/**,dist/**,coverage/**,.scannerwork/**,artifacts/**,reports/**,playwright-report/**,test-results/**,db/**,tests/**
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
